FROM ubuntu

COPY server.zip server.zip
RUN apt-get update
RUN apt-get -y install unzip
RUN apt-get install -y dotnet-sdk-7.0
RUN apt-get install -y libfontconfig
RUN unzip server.zip
RUN rm -f server.zip
RUN chmod +x mdmc_server.x86_64

EXPOSE 8080/udp

ENTRYPOINT [ "./mdmc_server.x86_64", "--headless", "--playfab"]
