FROM ubuntu

WORKDIR /.docker

COPY server.zip server.zip
RUN apt-get update \
    && apt-get -y install unzip \
    && apt-get install -y dotnet-sdk-7.0 \
    && apt-get install -y libfontconfig \
    && unzip "${{ github.workspace }}/server.zip" -d /Server \
    && rm -f server.zip \
    && chmod +x /Server/Server.x86_64

EXPOSE 8080/udp

ENTRYPOINT [ "./Server.x86_64", "--headless", "--playfab"]
