FROM ubuntu

COPY server.zip server.zip
RUN apt-get update
RUN apt-get -y install unzip
RUN apt-get install -y dotnet-sdk-7.0
RUN apt-get install -y libfontconfig
RUN unzip server.zip -d server/
RUN rm -f server.zip
RUN chmod +x server/Server.x86_64

WORKDIR /Server

EXPOSE 8080/udp

ENTRYPOINT [ "./Server.x86_64", "--headless", "--playfab"]
