name: Build and deploy Daikon Connect

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Build Application
      run: dotnet build Daikon/Daikon/Daikon.csproj --configuration Release

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DAIKON_DOCKERUSERNAME }}
        password: ${{ secrets.DAIKON_DOCKERPASS }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DAIKON_DOCKERUSERNAME }}/daikonconnect:latest -f Daikon/dockerfile .
        docker push ${{ secrets.DAIKON_DOCKERUSERNAME }}/daikonconnect:latest

    - name: SSH into Server and Update Docker Container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS1_SSH_HOST }}
        username: root
        password: ${{ secrets.VPS1_SSH_PASS }}
        script: |
          docker login -u "${{ secrets.DAIKON_DOCKERUSERNAME }}" -p "${{ secrets.DAIKON_DOCKERPASS }}"
          docker stop $(docker ps -a -q) 
          docker rmi -f $(docker images -aq)
          docker pull ${{ secrets.DAIKON_DOCKERUSERNAME }}/daikonconnect:latest
          nohup docker run -p 5000:5000 ${{ secrets.DAIKON_DOCKERUSERNAME }}/daikonconnect:latest /dev/null 2>&1 &
          logout
